trigger:
- main

pool: 'Default'


steps:
- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'private-aks-cluster-test-service-connection'
    namespace: 'default'
    command: login
