trigger:
- main

resources:
- repo: self


pool: 'Default'

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'manual-connection-to-the-container-registry'
  imageRepository: 'awaghadpdtest'
  containerRegistry: 'prajwalnewacr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'prajwalnewacr9316e314-auth'

steps:
- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'private-aks-cluster-test-service-connection'
    namespace: 'ingress-basic'
    command: login
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sed -i ''s/\r$//'' ''./deploy.sh'''
    workingDirectory: "private-aks-test/"